import { useEffect, useRef, useState } from 'react';
import { API_BASE_URL, getAuthHeaders } from '../../utils/auth';

type TraceResult={name:string;farmName:string;farmAddress:string;seasonName?:string;harvestDate?:string;
  certifications:string[];transactionHash?:string;processes?:{processType:string;executionDate:string;materials?:string;notes?:string;transactionHash?:string}[]};

export default function QrScannerPage(){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),timer=useRef<number|null>(null);
 const [value,setValue]=useState(''),[error,setError]=useState(''),[scanning,setScanning]=useState(false),[result,setResult]=useState<TraceResult|null>(null);
 const stop=()=>{if(timer.current)window.clearInterval(timer.current);timer.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setScanning(false)};
 useEffect(()=>stop,[]);
 const lookup=async(raw:string)=>{const hash=raw.trim().split('/').filter(Boolean).pop()||'';if(!hash){setError('Mã QR không chứa mã truy xuất hợp lệ.');return}setError('');const r=await fetch(`${API_BASE_URL}/marketplace/products/trace/${encodeURIComponent(hash)}`,{headers:getAuthHeaders()});const b=await r.json().catch(()=>({}));if(!r.ok){setError(b.message||'Không tìm thấy sản phẩm từ mã QR.');return}setValue(raw);setResult(b);stop()};
 const detector=()=>{const D=(window as any).BarcodeDetector;if(!D)throw new Error('Trình duyệt này chưa hỗ trợ đọc QR. Hãy dùng Chrome/Edge mới hoặc dán liên kết truy xuất.');return new D({formats:['qr_code']})};
 const start=async()=>{try{setError('');const d=detector();stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});if(video.current)video.current.srcObject=stream.current;setScanning(true);timer.current=window.setInterval(async()=>{if(!video.current||video.current.readyState<2)return;const codes=await d.detect(video.current).catch(()=>[]);if(codes[0]?.rawValue)void lookup(codes[0].rawValue)},700)}catch(e){stop();setError(e instanceof Error?e.message:'Không thể mở camera.')}};
 const upload=async(file?:File)=>{if(!file)return;try{setError('');const image=await createImageBitmap(file);const codes=await detector().detect(image);image.close();if(!codes[0]?.rawValue)throw new Error('Không phát hiện mã QR trong ảnh.');await lookup(codes[0].rawValue)}catch(e){setError(e instanceof Error?e.message:'Không thể đọc ảnh QR.')}};
 return <section style={wrap}><h1>Quét QR truy xuất nguồn gốc</h1><p style={muted}>Quét bằng camera, tải ảnh QR hoặc dán liên kết truy xuất được tạo khi xuất kho.</p><div style={actions}><button style={primary} onClick={scanning?stop:()=>void start()}>{scanning?'Dừng camera':'Mở camera'}</button><label style={uploadBtn}>Tải ảnh QR<input hidden type="file" accept="image/*" onChange={e=>void upload(e.target.files?.[0])}/></label><input style={input} placeholder="Dán liên kết hoặc trace hash" value={value} onChange={e=>setValue(e.target.value)}/><button style={secondary} onClick={()=>void lookup(value)}>Truy xuất</button></div>{scanning&&<video ref={video} autoPlay playsInline muted style={camera}/>} {error&&<div style={alert}>{error}</div>}{result&&<article style={panel}><p style={{color:'#34d399',fontWeight:700}}>✓ Đã xác minh dữ liệu truy xuất</p><h2>{result.name}</h2><p>🏡 {result.farmName} · {result.farmAddress}</p><p>🌾 {result.seasonName||'Chưa cập nhật mùa vụ'} · Thu hoạch {result.harvestDate||'—'}</p><p>🏅 {result.certifications?.join(', ')||'Chưa cập nhật chứng nhận'}</p><p style={hash}>Blockchain TX: {result.transactionHash||'—'}</p><h3>Quy trình canh tác</h3>{result.processes?.length?result.processes.map((p,i)=><div key={i} style={timeline}><b>{p.executionDate} · {p.processType}</b><div>{p.materials||p.notes||'Không có ghi chú'}</div><small style={hash}>{p.transactionHash}</small></div>):<p style={muted}>Chưa có quy trình được ghi nhận.</p>}</article>}</section>;
}
const wrap:React.CSSProperties={color:'#e2e8f0'};const muted:React.CSSProperties={color:'#94a3b8'};const actions:React.CSSProperties={display:'flex',flexWrap:'wrap',gap:10,padding:18,border:'1px solid #334155',borderRadius:14,background:'#0f172a'};const primary:React.CSSProperties={border:0,borderRadius:8,padding:'10px 15px',background:'#10b981',color:'#fff',fontWeight:700,cursor:'pointer'};const secondary:React.CSSProperties={...primary,background:'#334155'};const uploadBtn:React.CSSProperties={...primary,display:'inline-block'};const input:React.CSSProperties={flex:'1 1 260px',padding:'10px 12px',borderRadius:8,border:'1px solid #475569',background:'#111827',color:'#fff'};const camera:React.CSSProperties={display:'block',width:'min(640px,100%)',margin:'18px auto',borderRadius:16,border:'2px solid #10b981'};const alert:React.CSSProperties={marginTop:16,padding:12,border:'1px solid #ef4444',borderRadius:8,color:'#fecaca'};const panel:React.CSSProperties={marginTop:18,padding:24,border:'1px solid #334155',borderRadius:14,background:'#0f172a'};const timeline:React.CSSProperties={borderLeft:'2px solid #10b981',padding:'4px 0 14px 14px'};const hash:React.CSSProperties={color:'#94a3b8',fontFamily:'monospace',overflowWrap:'anywhere'};
